const properties = [
{id:1,title:'Family Maisonette Near General Waruinge Street',category:'Houses',intent:'Buy',location:'Eastleigh Section 1',area:'General Waruinge corridor',price:26800000,priceType:'sale',beds:4,baths:3,size:'232m²',image:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1100&q=80',badge:'Verified Sale',description:'Corner maisonette in a secure court with steady water and covered parking.',features:['Parking','Family Friendly']},
{id:2,title:'Newly Renovated 2 Bedroom Apartment — Eastleigh Section 1',category:'Apartments',intent:'Rent',location:'Eastleigh Section 1',area:'2nd Avenue',price:58000,priceType:'month',beds:2,baths:2,size:'116m²',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Recently updated unit with fitted kitchen and balcony facing the avenue.',features:['Furnished','Parking']},
{id:3,title:'Serviced Studio Apartment — Pangani',category:'Apartments',intent:'Rent',location:'Pangani',area:'Pumwani link road',price:22000,priceType:'month',beds:0,baths:1,size:'42m²',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Compact studio with caretaker support and reliable public transport access.',features:['New Development']},
{id:4,title:'1/8 Acre Plot Off Spine Road',category:'Land / Plots',intent:'Buy',location:'Kayole corridor',area:'Spine Road edge',price:4800000,priceType:'sale',beds:0,baths:0,size:'1/8 acre',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Serviced residential plot suitable for a mid-rise rental block.',features:['Family Friendly']},
{id:5,title:'3 Bedroom Apartment Near Pangani Girls',category:'Apartments',intent:'Rent',location:'Pangani',area:'Pangani gardens lane',price:92000,priceType:'month',beds:3,baths:2,size:'172m²',image:'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Large apartment with lift access, backup water and two parking slots.',features:['Parking','Family Friendly']},
{id:6,title:'Mixed-Use Commercial Plot Near Juja Road',category:'Land / Plots',intent:'Buy',location:'Juja Road corridor',area:'Main road frontage',price:119000000,priceType:'sale',beds:0,baths:0,size:'0.44 acres',image:'https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1100&q=80',badge:'Commercial',description:'Prime frontage plot zoned for retail, offices and upper-floor apartments.',features:['Commercial Use']},
{id:7,title:'2 Bedroom Apartment in New Block — Section 3',category:'Apartments',intent:'Buy',location:'Eastleigh Section 3',area:'3rd Avenue',price:10300000,priceType:'sale',beds:2,baths:2,size:'126m²',image:'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Contemporary plan with lift, borehole and controlled entry lobby.',features:['New Development','Parking']},
{id:8,title:'5 Bedroom Townhouse on Muhoho Avenue',category:'Houses',intent:'Buy',location:'South C',area:'Muhoho Avenue',price:43800000,priceType:'sale',beds:5,baths:4,size:'340m²',image:'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Multi-level townhouse ideal for larger families and diplomatic tenants.',features:['Parking','Family Friendly']}
];
const $=s=>document.querySelector(s);const grid=$('#featuredGrid'),chips=$('#chipsRow'),result=$('#resultCount');
const state={intent:'Buy',search:'',type:'All Types',min:'',max:'',beds:0,baths:0,location:'',featuredOnly:false,parking:false,family:false,sort:'newest',visible:window.innerWidth<=768?6:8,saved:new Set(JSON.parse(localStorage.getItem('eastleigh_saved_properties')||'[]')),recent:JSON.parse(localStorage.getItem('eastleigh_recently_viewed')||'[]'),compare:[],activePropertyId:null};
const formatPrice=(p,t)=>`KSh ${p.toLocaleString()}${t==='month'?' / month':''}`;const featured=p=>p.features.includes('New Development')||p.badge.includes('Verified');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
function filtered(){return properties.filter(p=>{if(state.intent==='Land / Plots'?p.category!=='Land / Plots':p.intent!==state.intent)return false; if(state.type!=='All Types'&&p.category!==state.type)return false; if(state.min&&p.price<+state.min)return false;if(state.max&&p.price>+state.max)return false;if(state.beds&&p.beds<state.beds)return false;if(state.baths&&p.baths<state.baths)return false;if(state.location&&!p.location.toLowerCase().includes(state.location.toLowerCase()))return false;if(state.featuredOnly&&!featured(p))return false;if(state.parking&&!p.features.includes('Parking'))return false;if(state.family&&!p.features.includes('Family Friendly'))return false;const hay=(p.title+p.location+p.area+p.description).toLowerCase();return !state.search||hay.includes(state.search.toLowerCase())})}
function sorted(list){const arr=[...list];if(state.sort==='price-low')arr.sort((a,b)=>a.price-b.price);if(state.sort==='price-high')arr.sort((a,b)=>b.price-a.price);if(state.sort==='beds')arr.sort((a,b)=>b.beds-a.beds);if(state.sort==='featured')arr.sort((a,b)=>Number(featured(b))-Number(featured(a)));if(state.sort==='newest')arr.sort((a,b)=>b.id-a.id);return arr}
function renderSkeleton(){grid.innerHTML=Array.from({length:4},()=>'<div class="skeleton"></div>').join('')}
function activeChips(){const out=[];if(state.type!=='All Types')out.push(['type',state.type]);if(state.beds)out.push(['beds',`${state.beds}+ Beds`]);if(state.max)out.push(['max',`Under ${(+state.max).toLocaleString()}`]);if(state.parking)out.push(['parking','Parking']);if(state.family)out.push(['family','Family Friendly']);return out}
function render(){renderSkeleton();setTimeout(()=>{const list=sorted(filtered());const shown=list.slice(0,state.visible);grid.innerHTML=shown.length?shown.map(p=>`<article class="property-card" data-property-id="${p.id}"><img src="${p.image}"><span class="badge">${p.badge}</span><div class="card-actions"><button class="icon-btn" data-fav="${p.id}">${state.saved.has(p.id)?'♥':'♡'}</button><button class="icon-btn" data-comp="${p.id}">${state.compare.includes(p.id)?'✓':'⇄'}</button><button class="icon-btn" data-share="${p.id}">↗</button></div><div class="card-body"><h3>${p.title}</h3><p>${p.location}</p><strong>${formatPrice(p.price,p.priceType)}</strong><small>${p.beds} Beds · ${p.baths} Baths · ${p.size}</small><button class="btn btn-gold" data-open="${p.id}">View</button></div></article>`).join(''):'<article class="empty-state"><h3>No matching properties found</h3><button class="btn btn-gold" id="resetEmpty">Reset filters</button></article>';result.textContent=`${list.length} Properties Found`;chips.innerHTML=activeChips().map(([k,v])=>`<span class="chip">${v}<button data-chip="${k}">×</button></span>`).join('')+(activeChips().length?'<button class="chip" id="clearAll">Clear All</button>':'');$('#loadMoreBtn').style.display=list.length>state.visible?'inline-block':'none';renderCompareBar()},180)}
function clearAll(){Object.assign(state,{type:'All Types',min:'',max:'',beds:0,baths:0,location:'',featuredOnly:false,parking:false,family:false,visible:window.innerWidth<=768?6:8});syncControls();render()}
function shareProperty(id){const url=`${location.origin}${location.pathname}#property-${id}`;const p=properties.find(x=>x.id===id);if(navigator.share){navigator.share({title:p.title,text:p.title,url}).catch(()=>{});return;}navigator.clipboard.writeText(url).then(()=>toast('Link copied'))}
function renderCompareBar(){const bar=$('#compareBar');if(!state.compare.length){bar.classList.remove('visible');bar.innerHTML='';return;}bar.classList.add('visible');bar.innerHTML=`<strong>${state.compare.length}/3 selected</strong><button class="btn" id="openCompare">Compare</button><button class="btn" id="clearCompare">Clear</button>`}
function openModal(id){state.activePropertyId=id;history.pushState({propertyId:id},'',`#property-${id}`);const p=properties.find(x=>x.id===id);const m=document.createElement('div');m.id='propertyDetailModal';m.className='property-modal-backdrop';m.innerHTML=`<section class="property-modal"><button class="modal-close">×</button><div class="modal-media"><img src="${p.image}"></div><div class="modal-content"><div class="modal-body"><h3>${p.title}</h3><p>${p.location}</p><strong>${formatPrice(p.price,p.priceType)}</strong><p>${p.description}</p><div class="modal-actions"><button class="btn btn-gold" data-share="${p.id}">Share</button><button class="btn btn-gold schedule-viewing">Schedule Viewing</button></div><section class="inquiry-form-shell" id="inquiryFormSection"><form id="inquiryForm"><input required placeholder="Name"><input required placeholder="Phone"><button class="btn btn-gold">Submit Request</button></form></section></div></div></section>`;document.body.appendChild(m);document.body.classList.add('modal-open')}
function closeModal(){document.getElementById('propertyDetailModal')?.remove();document.body.classList.remove('modal-open');state.activePropertyId=null}
function syncControls(){['#searchInput','#stickySearchInput'].forEach(s=>$(s).value=state.search);$('#typeFilter').value=state.type;$('#minPrice').value=state.min;$('#maxPrice').value=state.max;$('#bedsFilter').value=state.beds;$('#sortSelect').value=state.sort}
$('#openAdvancedBtn').onclick=()=>{if(window.innerWidth<=960){$('#advDrawer').classList.add('open');$('#advBackdrop').classList.add('open');document.body.classList.add('drawer-open')}};$('#advBackdrop').onclick=()=>{$('#advDrawer').classList.remove('open');$('#advBackdrop').classList.remove('open');document.body.classList.remove('drawer-open')}
$('#advancedInline').innerHTML=$('#advDrawer').innerHTML='<input id="advLocation" placeholder="Location"><select id="advBaths"><option value="0">Any Baths</option><option value="1">1+</option><option value="2">2+</option><option value="3">3+</option></select><label><input id="advFeatured" type="checkbox"> Featured only</label><label><input id="advParking" type="checkbox"> Parking</label><label><input id="advFamily" type="checkbox"> Family friendly</label>'
document.addEventListener('input',e=>{if(e.target.matches('#searchInput,#stickySearchInput')){state.search=e.target.value;state.visible=window.innerWidth<=768?6:8;syncControls();render()} if(e.target.id==='minPrice')state.min=e.target.value;if(e.target.id==='maxPrice')state.max=e.target.value;if(e.target.id==='advLocation')state.location=e.target.value;if(e.target.id==='advBaths')state.baths=+e.target.value;if(e.target.id==='advFeatured')state.featuredOnly=e.target.checked;if(e.target.id==='advParking')state.parking=e.target.checked;if(e.target.id==='advFamily')state.family=e.target.checked;});
document.addEventListener('change',e=>{if(e.target.id==='typeFilter')state.type=e.target.value;if(e.target.id==='bedsFilter')state.beds=+e.target.value;if(e.target.id==='sortSelect')state.sort=e.target.value;render()});
document.addEventListener('click',e=>{if(e.target.id==='searchBtn'||e.target.id==='stickySearchBtn')render();if(e.target.id==='loadMoreBtn'){state.visible+=window.innerWidth<=768?4:4;render()}if(e.target.dataset.fav){const id=+e.target.dataset.fav;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('eastleigh_saved_properties',JSON.stringify([...state.saved]));render()}if(e.target.dataset.comp){const id=+e.target.dataset.comp;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<3)state.compare.push(id);else toast('Maximum 3 properties');renderCompareBar();render()}if(e.target.dataset.share)shareProperty(+e.target.dataset.share);if(e.target.dataset.open)openModal(+e.target.dataset.open);if(e.target.classList.contains('modal-close')||e.target.id==='propertyDetailModal')closeModal();if(e.target.id==='clearAll'||e.target.id==='resetEmpty')clearAll();if(e.target.dataset.chip){if(e.target.dataset.chip==='type')state.type='All Types';if(e.target.dataset.chip==='beds')state.beds=0;if(e.target.dataset.chip==='max')state.max='';if(e.target.dataset.chip==='parking')state.parking=false;if(e.target.dataset.chip==='family')state.family=false;syncControls();render()}if(e.target.id==='openCompare'){const rows=state.compare.map(id=>properties.find(p=>p.id===id)).map(p=>`<td><img src="${p.image}" style="width:100%"><h4>${p.title}</h4><p>${formatPrice(p.price,p.priceType)}</p><p>${p.beds} Beds · ${p.baths} Baths · ${p.size}</p><p>${p.location}</p><p>${p.features.join(', ')}</p><button class='btn' data-comp='${p.id}'>Remove</button></td>`).join('');const m=document.createElement('div');m.id='propertyDetailModal';m.className='property-modal-backdrop';m.innerHTML=`<section class='property-modal' style='display:block;padding:16px;overflow:auto'><button class='modal-close'>×</button><table><tr>${rows}</tr></table></section>`;document.body.appendChild(m);document.body.classList.add('modal-open')}if(e.target.id==='clearCompare'){state.compare=[];renderCompareBar();render()}});
window.addEventListener('scroll',()=>$('#stickySearch').classList.toggle('visible',document.querySelector('.hero').getBoundingClientRect().bottom<100));
window.addEventListener('popstate',()=>{const m=location.hash.match(/#property-(\d+)/);if(m)openModal(+m[1]);else closeModal()});
render();
