const toggle = document.querySelector('.menu-toggle');
const drawer = document.getElementById('mobileDrawer');

const properties = [
{id:1,title:'Family Maisonette Near General Waruinge Street',category:'Houses',intent:'Buy',location:'Eastleigh Section 1',area:'General Waruinge corridor',price:26800000,priceType:'sale',beds:4,baths:3,size:'232m²',image:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1100&q=80',badge:'Verified Sale',description:'Corner maisonette in a secure court with steady water and covered parking.',features:['Parking','Family Friendly']},
{id:2,title:'Newly Renovated 2 Bedroom Apartment — Eastleigh Section 1',category:'Apartments',intent:'Rent',location:'Eastleigh Section 1',area:'2nd Avenue',price:58000,priceType:'month',beds:2,baths:2,size:'116m²',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Recently updated unit with fitted kitchen and balcony facing the avenue.',features:['Furnished','Parking']},
{id:3,title:'Serviced Studio Apartment — Pangani',category:'Apartments',intent:'Rent',location:'Pangani',area:'Pumwani link road',price:22000,priceType:'month',beds:0,baths:1,size:'42m²',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Compact studio with caretaker support and reliable public transport access.',features:['New Development']},
{id:4,title:'1/8 Acre Plot Off Spine Road',category:'Land / Plots',intent:'Buy',location:'Kayole corridor',area:'Spine Road edge',price:4800000,priceType:'sale',beds:0,baths:0,size:'1/8 acre',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Serviced residential plot suitable for a mid-rise rental block.',features:['Family Friendly']},
{id:5,title:'3 Bedroom Apartment Near Pangani Girls',category:'Apartments',intent:'Rent',location:'Pangani',area:'Pangani gardens lane',price:92000,priceType:'month',beds:3,baths:2,size:'172m²',image:'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Large apartment with lift access, backup water and two parking slots.',features:['Parking','Family Friendly']},
{id:6,title:'Mixed-Use Commercial Plot Near Juja Road',category:'Land / Plots',intent:'Buy',location:'Juja Road corridor',area:'Main road frontage',price:119000000,priceType:'sale',beds:0,baths:0,size:'0.44 acres',image:'https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1100&q=80',badge:'Commercial',description:'Prime frontage plot zoned for retail, offices and upper-floor apartments.',features:['Commercial Use']},
{id:7,title:'2 Bedroom Apartment in New Block — Section 3',category:'Apartments',intent:'Buy',location:'Eastleigh Section 3',area:'3rd Avenue',price:10300000,priceType:'sale',beds:2,baths:2,size:'126m²',image:'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Contemporary plan with lift, borehole and controlled entry lobby.',features:['New Development','Parking']},
{id:8,title:'5 Bedroom Townhouse on Muhoho Avenue',category:'Houses',intent:'Buy',location:'South C',area:'Muhoho Avenue',price:43800000,priceType:'sale',beds:5,baths:4,size:'340m²',image:'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Multi-level townhouse ideal for larger families and diplomatic tenants.',features:['Parking','Family Friendly']},
{id:9,title:'1 Bedroom Apartment — California Estate',category:'Apartments',intent:'Rent',location:'California Estate',area:'Starehe lane',price:30000,priceType:'month',beds:1,baths:1,size:'70m²',image:'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Well-maintained one-bedroom with tiled floors and fitted wardrobes.',features:['Family Friendly']},
{id:10,title:'3 Bedroom Maisonette in Buru Buru Phase 3',category:'Houses',intent:'Rent',location:'Buru Buru',area:'Phase 3',price:102000,priceType:'month',beds:3,baths:3,size:'214m²',image:'https://images.unsplash.com/photo-1472224371017-08207f84aaae?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Standalone maisonette with perimeter wall and ample parking yard.',features:['Parking','Family Friendly']},
{id:11,title:'2 Bedroom Apartment on Parklands Edge',category:'Apartments',intent:'Buy',location:'Parklands edge',area:'Ngara connector',price:12900000,priceType:'sale',beds:2,baths:2,size:'132m²',image:'https://images.unsplash.com/photo-1560185009-dddeb820c7b7?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Ideal investor unit close to CBD links, hospitals and universities.',features:['Furnished','Parking']},
{id:12,title:'Warehouse-Retail Development Parcel',category:'Land / Plots',intent:'Buy',location:'Eastleigh Section 2',area:'Juja Road service lane',price:82000000,priceType:'sale',beds:0,baths:0,size:'0.31 acres',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1100&q=80',badge:'Investment',description:'Commercial parcel suited for warehousing with retail frontage.',features:['Commercial Use']},
{id:13,title:'Luxury 3 Bedroom Apartment — Pangani Riverside',category:'Apartments',intent:'Buy',location:'Pangani',area:'Riverside edge',price:17600000,priceType:'sale',beds:3,baths:3,size:'188m²',image:'https://images.unsplash.com/photo-1560185009-dddeb820c7b7?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Premium three-bedroom with ensuite rooms and skyline-facing lounge.',features:['New Development','Parking']},
{id:14,title:'Studio Loft Unit Near 6th Street',category:'Apartments',intent:'Rent',location:'Eastleigh Section 3',area:'6th Street',price:25000,priceType:'month',beds:0,baths:1,size:'45m²',image:'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1100&q=80',badge:'For Rent',description:'Loft-style studio with fitted kitchenette and secure main entrance.',features:['Furnished']},
{id:15,title:'Detached 4 Bedroom House — California Estate',category:'Houses',intent:'Buy',location:'California Estate',area:'Inner loop',price:33200000,priceType:'sale',beds:4,baths:3,size:'272m²',image:'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1100&q=80',badge:'For Sale',description:'Detached home with mature garden, servant quarter and private driveway.',features:['Parking','Family Friendly']},
{id:16,title:'High-Density Redevelopment Plot — Section 1',category:'Land / Plots',intent:'Buy',location:'Eastleigh Section 1',area:'First Avenue commercial belt',price:168000000,priceType:'sale',beds:0,baths:0,size:'0.62 acres',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1100&q=80',badge:'Prime Plot',description:'Rare Eastleigh core plot ideal for mixed-use high-rise redevelopment.',features:['Commercial Use','New Development']}
];
// keep rest same
const state = { intent: 'Buy', search: '', type: 'All Types', min: '', max: '', beds: 0, features: [] };
const grid = document.getElementById('featuredGrid'); const categoryCards = document.getElementById('categoryCards'); const resultCount = document.getElementById('resultCount');
const formatPrice=(p,t)=>`KSh ${p.toLocaleString()}${t==='month'?' / month':''}`;
function applyFilters(){return properties.filter((p)=>{if(state.intent==='Land / Plots'){if(p.category!=='Land / Plots')return false;} else if(p.intent!==state.intent)return false; if(state.type!=='All Types'&&p.category!==state.type)return false; if(state.min&&p.price<Number(state.min))return false; if(state.max&&p.price>Number(state.max))return false; if(state.beds>0&&p.category!=='Land / Plots'&&p.beds<state.beds)return false; if(state.features.length&&!state.features.every(f=>p.features.includes(f)))return false; const hay=`${p.title} ${p.location} ${p.category} ${p.area} ${p.features.join(' ')} ${p.description}`.toLowerCase(); if(state.search&&!hay.includes(state.search.toLowerCase()))return false; return true;});}
function renderCategories(filtered){const cards=[{name:'Houses',count:filtered.filter(p=>p.category==='Houses').length,img:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'},{name:'Apartments',count:filtered.filter(p=>p.category==='Apartments').length,img:'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80'},{name:'Land / Plots',count:filtered.filter(p=>p.category==='Land / Plots').length,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'},{name:'Commercial Spaces',count:filtered.filter(p=>p.features.includes('Commercial Use')).length,img:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80'},{name:'Rental Units',count:filtered.filter(p=>p.intent==='Rent').length,img:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'}];categoryCards.innerHTML=cards.map(c=>`<article class="image-card"><img src="${c.img}" alt="${c.name}"/><div><h3>${c.name}</h3><p>${c.count} listings</p></div></article>`).join('');}
function render(){const filtered=applyFilters(); if(!filtered.length){grid.innerHTML=`<article class="empty-state"><h3>No matching properties found</h3><p>Try broadening your search or reset the filters.</p><button id="clearFromEmpty" class="btn btn-gold">Clear filters</button></article>`;} else {grid.innerHTML=filtered.slice(0,8).map(p=>`<article class="property-card"><img src="${p.image}" alt="${p.title}"/><span class="badge ${p.priceType==='month'?'rent':''}">${p.badge}</span><button class="fav">♡</button><div class="card-body"><h3>${p.title}</h3><p>${p.location} · ${p.area}</p><strong>${formatPrice(p.price,p.priceType)}</strong><small>${p.category==='Land / Plots'?p.size:`${p.beds} Beds · ${p.baths} Baths · ${p.size}`}</small><em>${p.description}</em></div></article>`).join('');}
resultCount.textContent=`${filtered.length} ${state.intent==='Rent'?'rentals':state.intent==='Land / Plots'?'land / plots':'properties'} shown`;renderCategories(filtered);document.getElementById('clearFromEmpty')?.addEventListener('click',clearFilters)}
function clearFilters(){state.search='';state.type='All Types';state.min='';state.max='';state.beds=0;state.features=[];searchInput.value='';typeFilter.value='All Types';minPrice.value='';maxPrice.value='';bedsFilter.value='0';document.querySelectorAll('#moreFilters input').forEach(i=>i.checked=false);render();}
toggle?.addEventListener('click',()=>drawer.classList.toggle('open'));document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.intent=btn.dataset.intent;render();}));
searchInput.addEventListener('input',e=>{state.search=e.target.value;render();});typeFilter.addEventListener('change',e=>{state.type=e.target.value;render();});minPrice.addEventListener('input',e=>{state.min=e.target.value;render();});maxPrice.addEventListener('input',e=>{state.max=e.target.value;render();});bedsFilter.addEventListener('change',e=>{state.beds=Number(e.target.value);render();});moreFiltersBtn.addEventListener('click',()=>moreFilters.classList.toggle('open'));document.querySelectorAll('#moreFilters input').forEach(i=>i.addEventListener('change',()=>{state.features=[...document.querySelectorAll('#moreFilters input:checked')].map(n=>n.value);render();}));document.getElementById('clearFilters').addEventListener('click',clearFilters);
render();
